# Generated by Django 4.0.6 on 2022-07-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homebg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Homebg name')),
                ('about', models.TextField(verbose_name='Homebg about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Homebg image ')),
            ],
            options={
                'verbose_name': 'Homebg',
                'verbose_name_plural': 'Homebgs',
            },
        ),
    ]
